# SPDX-License-Identifier: CC0-1.0
# Calamares settings.conf — Roudix
---
modules-search: [ local, /run/current-system/sw/lib/calamares/modules ]

instances:
  - id:     gpu
    module: packagechooser
    config: packagechooser-gpu.conf
  - id:     nvidialaptop
    module: packagechooser
    config: packagechooser-nvidialaptop.conf
  - id:     cpu
    module: packagechooser
    config: packagechooser-cpu.conf
  - id:     vmguest
    module: packagechooser
    config: packagechooser-vmguest.conf
  - id:     kernel
    module: packagechooser
    config: packagechooser-kernel.conf
  - id:     browser
    module: packagechooser
    config: packagechooser-browser.conf
  - id:     bravevariant
    module: packagechooser
    config: packagechooser-bravevariant.conf
  - id:     zen
    module: packagechooser
    config: packagechooser-zen.conf
  - id:     desktop
    module: packagechooser
    config: packagechooser-desktop.conf
  - id:     shell
    module: packagechooser
    config: packagechooser-shell.conf
  - id:     shelldefault
    module: packagechooser
    config: packagechooser-shelldefault.conf
  - id:     gaming
    module: packagechooser
    config: packagechooser-gaming.conf
  - id:     gtafix
    module: packagechooser
    config: packagechooser-gtafix.conf
  - id:     flatpak
    module: packagechooser
    config: packagechooser-flatpak.conf
  - id:     virtualization
    module: packagechooser
    config: packagechooser-virtualization.conf
  - id:     autoupdate
    module: packagechooser
    config: packagechooser-autoupdate.conf
  - id:     autoupdateinterval
    module: packagechooser
    config: packagechooser-autoupdateinterval.conf
  - id:     bootloader
    module: packagechooser
    config: packagechooser-bootloader.conf
  - id:     matrix
    module: packagechooser
    config: packagechooser-matrix.conf
  - id:     waydroid
    module: packagechooser
    config: packagechooser-waydroid.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - users
    - packagechooser@gpu
    - packagechooser@nvidialaptop
    - packagechooser@cpu
    - packagechooser@vmguest
    - packagechooser@kernel
    - packagechooser@browser
    - packagechooser@bravevariant
    - packagechooser@zen
    - packagechooser@desktop
    - packagechooser@shell
    - packagechooser@shelldefault
    - packagechooser@gaming
    - packagechooser@gtafix
    - packagechooser@flatpak
    - packagechooser@virtualization
    - packagechooser@autoupdate
    - packagechooser@autoupdateinterval
    - packagechooser@bootloader
    - packagechooser@matrix
    - packagechooser@waydroid
    - partition
    - summary
  - exec:
    - partition
    - mount
    - nixos
    - users
    - umount
  - show:
    - finished

branding: roudix

prompt-install:                 false
dont-chroot:                    false
oem-setup:                      false
disable-cancel:                 false
disable-cancel-during-exec:     true
hide-back-and-next-during-exec: false
quit-at-end:                    false
