# SPDX-License-Identifier: CC0-1.0
# Calamares settings.conf — Roudix
---
modules-search: [ local, /run/current-system/sw/lib/calamares/modules ]

instances: []

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - users
    - roudixoptions
    - roudixsoftware
    - roudixextras
    - partition
    - summary
  - exec:
    - partition
    - mount
    - nixos
    - users
    - umount
  - show:
    - finished

branding: roudix

prompt-install:                 false
dont-chroot:                    false
oem-setup:                      false
disable-cancel:                 false
disable-cancel-during-exec:     true
hide-back-and-next-during-exec: false
quit-at-end:                    false
