# SPDX-License-Identifier: CC0-1.0
# Calamares settings.conf — Roudix
---
modules-search: [ local ]

instances:
  - id:     desktop
    module: packagechooser
    config: packagechooser-desktop.conf
  - id:     shell
    module: packagechooser
    config: packagechooser-shell.conf
  - id:     kernel
    module: packagechooser
    config: packagechooser-kernel.conf
  - id:     browser
    module: packagechooser
    config: packagechooser-browser.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - users
    - packagechooser@desktop
    - packagechooser@shell
    - packagechooser@kernel
    - packagechooser@browser
    - partition
    - summary
  - exec:
    - partition
    - mount
    - nixos
    - users
    - umount
  - show:
    - finished

branding: roudix

prompt-install:                 false
dont-chroot:                    false
oem-setup:                      false
disable-cancel:                 false
disable-cancel-during-exec:     true
hide-back-and-next-during-exec: false
quit-at-end:                    false
