gappih=9
gappiv=9
gappoh=9
gappov=9

borderpx=2
border_radius=12   # plus safe
no_radius_when_single=1

focused_opacity=1.0
unfocused_opacity=0.95

# Blur
blur=1
blur_params_num_passes=3
blur_params_radius=6
blur_params_brightness=0.9
blur_params_contrast=0.9
blur_params_saturation=1.1

# Shadows
shadows=1
shadow_only_floating=0
shadows_size=10
shadows_blur=16
shadowscolor=0x00000055
