# ──────────────────────────────────────
# AUTOSTART
# ──────────────────────────────────────

# Shell / Wallpaper
exec-once=awww-daemon
exec-once=noctalia-shell --no-duplicate

# Apps
exec-once=discord
exec-once=openrgb


# XDG Desktop Portal — nécessaire pour Pipewire screen capture (OBS, Discord Go Live...)
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
