# DBus / environnement
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=mango

# XWayland (optionnel selon build)
exec-once = Xwayland

# Wallpaper
exec-once = swww-daemon
exec-once = swww img ~/Images/wallpaper.jpg

# Shell
exec-once = noctalia-shell --no-duplicate

# Polkit
exec-once = /run/current-system/sw/libexec/polkit-gnome-authentication-agent-1 &

# Apps
exec-once = discord --start-minimized
exec-once = openrgb
