# ──────────────────────────────────────
# INPUT — KEYBOARD
# ──────────────────────────────────────
xkb_rules_layout=us
xkb_rules_variant=intl
numlockon=1


# ──────────────────────────────────────
# INPUT — SOURIS
# ──────────────────────────────────────
# accel_profile flat (Hyprland: accel_profile=flat → MangoWC: 1=Flat)
accel_profile=1


# ──────────────────────────────────────
# INPUT — TOUCHPAD
# ──────────────────────────────────────
tap_to_click=1
trackpad_natural_scrolling=1
