# SPDX-License-Identifier: CC0-1.0
# Configuration du module partition — Roudix
---
efiSystemPartition: "/boot"
efiSystemPartitionSize: 512MiB
efiSystemPartitionName: ESP

userSwapChoices:
    - none
    - small
    - suspend
    - file

initialPartitioningChoice: erase
initialSwapChoice: none

defaultFileSystemType: "ext4"

availableFileSystemTypes: [ "ext4", "btrfs", "xfs" ]

enableLuksAutomatedPartitioning: true

drawNestedPartitions: false
alwaysShowPartitionLabels: true

allowManualPartitioning: true

unsafePartitionTypes: false
