# SPDX-License-Identifier: CC0-1.0
# Configuration du module users — Roudix
---
displayAutologin: true
doAutologin: false

hostname:
  location: None

defaultGroups:
  - name: networkmanager
    must_exist: false
    system: true
  - name: wheel
    must_exist: false
    system: true
  - name: disk
    must_exist: false
    system: true
  - name: input
    must_exist: false
    system: true
  - name: render
    must_exist: false
    system: true
  - name: video
    must_exist: false
    system: true
  - name: audio
    must_exist: false
    system: true
  - name: scanner
    must_exist: false
    system: true
  - name: lp
    must_exist: false
    system: true

userShell: /run/current-system/sw/bin/bash
