# SPDX-License-Identifier: CC0-1.0
# Écran d'accueil — Roudix
---
showSupportUrl: true
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false

requirements:
  requiredStorage: 40
  requiredRam: 4.0

  internetCheckUrl:
    - https://cache.nixos.org/
    - https://roudix.cachix.org/

  check:
    - storage
    - ram
    - power
    - internet
    - screen

  required:
    - storage
    - ram
    - internet
