# SPDX-License-Identifier: CC0-1.0
# Flatpak — Roudix
---
mode: required
method: legacy
labels:
  step: "Flatpak"

default: "false"

items:
  - id: "false"
    packages: []
    name: "Non"
    description: "Ne pas activer Flatpak"
  - id: "true"
    packages: []
    name: "Oui"
    description: "Activer Flatpak"
