# SPDX-License-Identifier: CC0-1.0
# Intervalle des mises à jour automatiques — Roudix
---
mode: required
method: legacy
labels:
  step: "Intervalle"

default: "1h"

items:
  - id: "1h"
    packages: []
    name: "Toutes les heures"
    description: "Vérifie les mises à jour toutes les heures"
  - id: "6h"
    packages: []
    name: "Toutes les 6 heures"
    description: "Vérifie les mises à jour toutes les 6 heures"
  - id: "12h"
    packages: []
    name: "Toutes les 12 heures"
    description: "Vérifie les mises à jour toutes les 12 heures"
  - id: "24h"
    packages: []
    name: "Une fois par jour"
    description: "Vérifie les mises à jour une fois par jour"
