# SPDX-License-Identifier: CC0-1.0
# Zen Browser — Roudix
---
mode: required
method: legacy
labels:
  step: "Zen Browser"

default: false

items:
  - id: false
    packages: []
    name: "Non"
    description: "Ne pas installer Zen Browser"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/no.png"
  - id: true
    packages: []
    name: "Oui"
    description: "Installer Zen Browser"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/yes.png"
