# SPDX-License-Identifier: CC0-1.0
# Environnement de bureau — Roudix
---
mode: required
method: legacy
labels:
  step: "Environnement de bureau"

default: niri

items:
  - id: niri
    packages: []
    name: "Niri ★"
    description: "Compositeur Wayland par défaut de Roudix (colonnes scrollables)"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/desktop/niri.png"
  - id: hyprland
    packages: []
    name: "Hyprland"
    description: "Compositeur Wayland dynamique très populaire"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/desktop/hyprland.png"
  - id: gnome
    packages: []
    name: "GNOME"
    description: "Bureau classique et intuitif"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/desktop/gnome.png"
  - id: plasma
    packages: []
    name: "KDE Plasma"
    description: "Bureau riche en fonctionnalités"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/desktop/plasma.png"
