# SPDX-License-Identifier: CC0-1.0
# Waydroid — Roudix
---
mode: required
method: legacy
labels:
  step: "Waydroid"

default: "false"

items:
  - id: "false"
    packages: []
    name: "Non"
    description: "Ne pas activer Waydroid"
  - id: "true"
    packages: []
    name: "Oui"
    description: "Activer Waydroid (conteneur Android)"
