# SPDX-License-Identifier: CC0-1.0
# Optimus (NVIDIA Laptop) — Roudix
---
mode: required
method: legacy
labels:
  step: "Optimus (NVIDIA Laptop)"

default: false

items:
  - id: false
    packages: []
    name: "Non — Desktop / NVIDIA seul"
    description: "Pas d'iGPU Intel/AMD"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/no.png"
  - id: true
    packages: []
    name: "Oui — Laptop Optimus"
    description: "iGPU Intel/AMD + dGPU NVIDIA"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/yes.png"
  - id: na
    packages: []
    name: "N/A — GPU non-NVIDIA"
    description: "Choisir si GPU AMD ou Intel"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/none.png"
