# SPDX-License-Identifier: CC0-1.0
# Mises à jour automatiques — Roudix
---
mode: required
method: legacy
labels:
  step: "Mises à jour automatiques"

default: true

items:
  - id: true
    packages: []
    name: "Oui ★"
    description: "Activer les MAJ automatiques"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/yes.png"
  - id: false
    packages: []
    name: "Non"
    description: "Gestion manuelle des MAJ"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/no.png"
