# SPDX-License-Identifier: CC0-1.0
# Machine virtuelle — Roudix
---
mode: required
method: legacy
labels:
  step: "VM"

default: "false"

items:
  - id: "false"
    packages: []
    name: "Non"
    description: "Installation sur machine physique"
  - id: "true"
    packages: []
    name: "Oui"
    description: "Activer les optimisations pour machine virtuelle"
