# SPDX-License-Identifier: CC0-1.0
# Shell de bureau — Roudix
---
mode: required
method: legacy
labels:
  step: "Shell de bureau"

default: noctalia

items:
  - id: noctalia
    packages: []
    name: "Noctalia ★"
    description: "Shell par défaut de Roudix"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/shell/noctalia.png"
  - id: dms
    packages: []
    name: "DankMaterialShell"
    description: "Design Material 3"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/shell/dms.png"
  - id: caelestia
    packages: []
    name: "Caelestia"
    description: "Setup Quickshell esthétique (Hyprland)"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/shell/caelestia.png"
  - id: na
    packages: []
    name: "N/A — GNOME/KDE"
    description: "Sélectionner si GNOME ou KDE Plasma"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/none.png"
