# SPDX-License-Identifier: CC0-1.0
# Navigateur — Roudix
---
mode: required
method: legacy
labels:
  step: "Navigateur"

default: brave

items:
  - id: none
    packages: []
    name: "Aucun"
    description: "Pas de navigateur préinstallé"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/browser/none.png"
  - id: brave
    packages: []
    name: "Brave"
    description: "Chromium + bloqueur de pub intégré"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/browser/brave.png"
  - id: helium
    packages: []
    name: "Helium"
    description: "Fork Chromium axé vie privée"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/browser/helium.png"
  - id: vivaldi
    packages: []
    name: "Vivaldi"
    description: "Navigateur très personnalisable"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/browser/vivaldi.png"
  - id: firefox
    packages: []
    name: "Firefox"
    description: "Navigateur libre de Mozilla"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/browser/firefox.png"
  - id: librewolf
    packages: []
    name: "LibreWolf"
    description: "Fork Firefox axé vie privée"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/browser/librewolf.png"
  - id: google-chrome
    packages: []
    name: "Google Chrome"
    description: "Navigateur propriétaire Google"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/browser/google-chrome.png"
  - id: microsoft-edge
    packages: []
    name: "Microsoft Edge"
    description: "Navigateur basé sur Chromium (Microsoft)"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/browser/microsoft-edge.png"
  - id: ungoogled-chromium
    packages: []
    name: "Ungoogled Chromium"
    description: "Chromium sans services Google"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/browser/ungoogled-chromium.png"
  - id: chromium
    packages: []
    name: "Chromium"
    description: "Base open-source de Chrome"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/browser/chromium.png"
