# SPDX-License-Identifier: CC0-1.0
# Brave — Variante — Roudix
---
mode: required
method: legacy
labels:
  step: "Brave — Variante"

default: brave

items:
  - id: brave
    packages: []
    name: "Stable ★"
    description: "Version stable recommandée"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/browser/brave.png"
  - id: brave-beta
    packages: []
    name: "Beta"
    description: "Version bêta"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/browser/brave.png"
  - id: brave-nightly
    packages: []
    name: "Nightly"
    description: "Bleeding edge"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/browser/brave.png"
  - id: brave-origin-beta
    packages: []
    name: "Origin Beta"
    description: "Variante Origin Beta"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/browser/brave.png"
  - id: brave-origin-nightly
    packages: []
    name: "Origin Nightly"
    description: "Variante Origin Nightly"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/browser/brave.png"
  - id: na
    packages: []
    name: "N/A — Pas Brave"
    description: "Sélectionner si non-Brave"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/none.png"
