# SPDX-License-Identifier: CC0-1.0
# Shell terminal par défaut — Roudix
---
mode: required
method: legacy
labels:
  step: "Shell terminal par défaut"

default: fish

items:
  - id: fish
    packages: []
    name: "Fish ★"
    description: "Shell intelligent, autocomplétion avancée"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/shell/fish.png"
  - id: bash
    packages: []
    name: "Bash"
    description: "Shell Unix classique"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/shell/bash.png"
