# SPDX-License-Identifier: CC0-1.0
# Machine Virtuelle — Roudix
---
mode: required
method: legacy
labels:
  step: "Machine Virtuelle"

default: false

items:
  - id: false
    packages: []
    name: "Non — Machine physique"
    description: "Installation bare-metal"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/no.png"
  - id: true
    packages: []
    name: "Oui — Activer options VM"
    description: "Optimisations pour VM"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/vm.png"
