# SPDX-License-Identifier: CC0-1.0
# Choix du CPU — Roudix
---
mode: required
method: legacy
labels:
  step: "CPU"

default: amd

items:
  - id: amd
    packages: []
    name: "AMD CPU"
    description: "Processeur AMD"
  - id: intel
    packages: []
    name: "Intel CPU"
    description: "Processeur Intel"
