# SPDX-License-Identifier: CC0-1.0
# Laptop NVIDIA Optimus — Roudix
---
mode: required
method: legacy
labels:
  step: "Optimus"

default: "false"

items:
  - id: "false"
    packages: []
    name: "Non"
    description: "Desktop ou NVIDIA seul (pas d'iGPU Intel/AMD)"
  - id: "true"
    packages: []
    name: "Oui"
    description: "Laptop avec iGPU Intel/AMD + dGPU NVIDIA (Optimus)"
