# SPDX-License-Identifier: CC0-1.0
# Paquets gaming — Roudix
---
mode: required
method: legacy
labels:
  step: "Paquets gaming"

default: true

items:
  - id: true
    packages: []
    name: "Oui ★"
    description: "Steam, Wine, Lutris, Proton..."
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/yes.png"
  - id: false
    packages: []
    name: "Non"
    description: "Pas de paquets gaming"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/no.png"
