# SPDX-License-Identifier: CC0-1.0
# Waydroid — Roudix
---
mode: required
method: legacy
labels:
  step: "Waydroid"

default: false

items:
  - id: false
    packages: []
    name: "Non"
    description: "Ne pas activer Waydroid"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/no.png"
  - id: true
    packages: []
    name: "Oui"
    description: "Conteneur Android sous Wayland"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/yes.png"
