# SPDX-License-Identifier: CC0-1.0
# Variante Brave — Roudix
---
mode: required
method: legacy
labels:
  step: "Brave"

default: brave

items:
  - id: brave
    packages: []
    name: "Stable (Recommandé)"
    description: "Version stable de Brave"
  - id: brave-beta
    packages: []
    name: "Beta"
    description: "Version bêta de Brave"
  - id: brave-nightly
    packages: []
    name: "Nightly"
    description: "Version nightly (bleeding edge) de Brave"
  - id: brave-origin-beta
    packages: []
    name: "Origin Beta"
    description: "Variante Origin Beta de Brave"
  - id: brave-origin-nightly
    packages: []
    name: "Origin Nightly"
    description: "Variante Origin Nightly de Brave"
