# SPDX-License-Identifier: CC0-1.0
# Client Matrix — Roudix
---
mode: required
method: legacy
labels:
  step: "Client Matrix"

default: none

items:
  - id: none
    packages: []
    name: "Aucun"
    description: "Pas de client Matrix"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/none.png"
  - id: element
    packages: []
    name: "Element Desktop"
    description: "Client Matrix complet"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/matrix/element.png"
  - id: cinny
    packages: []
    name: "Cinny"
    description: "Client Matrix léger"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/matrix/cinny.png"
