# SPDX-License-Identifier: CC0-1.0
# Shell par défaut — Roudix
---
mode: required
method: legacy
labels:
  step: "Shell par défaut"

default: fish

items:
  - id: fish
    packages: []
    name: "Fish (Recommandé)"
    description: "Shell intelligent et convivial"
  - id: bash
    packages: []
    name: "Bash"
    description: "Shell Unix classique"
