# SPDX-License-Identifier: CC0-1.0
# Fix GTA Online — Roudix
---
mode: required
method: legacy
labels:
  step: "Fix GTA Online"

default: false

items:
  - id: false
    packages: []
    name: "Non"
    description: "Ne pas activer"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/no.png"
  - id: true
    packages: []
    name: "Oui"
    description: "Bloque l'IP pour GTA Online sous Linux"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/yes.png"
