# SPDX-License-Identifier: CC0-1.0
# Virtualisation — Roudix
---
mode: required
method: legacy
labels:
  step: "Virtualisation"

default: "false"

items:
  - id: "false"
    packages: []
    name: "Non"
    description: "Ne pas activer la virtualisation"
  - id: "true"
    packages: []
    name: "Oui"
    description: "libvirt, virt-manager..."
