# SPDX-License-Identifier: CC0-1.0
# Installer Zen Browser — Roudix
---
mode: required
method: legacy
labels:
  step: "Zen Browser"

default: "false"

items:
  - id: "false"
    packages: []
    name: "Non"
    description: "Ne pas installer Zen Browser"
  - id: "true"
    packages: []
    name: "Oui"
    description: "Installer Zen Browser"
