# SPDX-License-Identifier: CC0-1.0
# Virtualisation — Roudix
---
mode: required
method: legacy
labels:
  step: "Virtualisation"

default: false

items:
  - id: false
    packages: []
    name: "Non"
    description: "Ne pas activer"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/no.png"
  - id: true
    packages: []
    name: "Oui"
    description: "libvirt, virt-manager..."
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/yes.png"
