# SPDX-License-Identifier: CC0-1.0
# Paquets gaming — Roudix
---
mode: required
method: legacy
labels:
  step: "Gaming"

default: "true"

items:
  - id: "true"
    packages: []
    name: "Oui"
    description: "Steam, Wine, Lutris..."
  - id: "false"
    packages: []
    name: "Non"
    description: "Pas de paquets gaming"
