# SPDX-License-Identifier: CC0-1.0
# Fix GTA Online — Roudix
---
mode: required
method: legacy
labels:
  step: "GTA Fix"

default: "false"

items:
  - id: "false"
    packages: []
    name: "Non"
    description: "Ne pas activer le fix GTA Online"
  - id: "true"
    packages: []
    name: "Oui"
    description: "Bloque l'IP pour jouer à GTA Online sous Linux"
