# SPDX-License-Identifier: CC0-1.0
# Intervalle des MAJ — Roudix
---
mode: required
method: legacy
labels:
  step: "Intervalle des MAJ"

default: 1h

items:
  - id: 1h
    packages: []
    name: "Toutes les heures"
    description: "Vérification toutes les heures"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/yes.png"
  - id: 6h
    packages: []
    name: "Toutes les 6 heures"
    description: "Vérification toutes les 6h"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/yes.png"
  - id: 12h
    packages: []
    name: "Toutes les 12 heures"
    description: "Vérification toutes les 12h"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/yes.png"
  - id: 24h
    packages: []
    name: "Une fois par jour"
    description: "Vérification quotidienne"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/yes.png"
  - id: na
    packages: []
    name: "N/A — MAJ désactivées"
    description: "Sélectionner si MAJ = Non"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/other/none.png"
