# SPDX-License-Identifier: CC0-1.0
# Bootloader — Roudix
---
mode: required
method: legacy
labels:
  step: "Bootloader"

default: limine

items:
  - id: limine
    packages: []
    name: "Limine ★"
    description: "Moderne, rapide, multi-disque"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/bootloader/limine.png"
  - id: systemd-boot
    packages: []
    name: "systemd-boot"
    description: "Bootloader UEFI simple"
    screenshot: "/run/current-system/sw/share/calamares/branding/roudix/assets/bootloader/systemd-boot.png"
