# SPDX-License-Identifier: CC0-1.0
# Bootloader — Roudix
---
mode: required
method: legacy
labels:
  step: "Bootloader"

default: limine

items:
  - id: limine
    packages: []
    name: "Limine (Recommandé)"
    description: "Moderne, rapide, support multi-disque"
  - id: systemd-boot
    packages: []
    name: "systemd-boot"
    description: "Bootloader UEFI simple"
