# SPDX-License-Identifier: CC0-1.0
# Mises à jour automatiques — Roudix
---
mode: required
method: legacy
labels:
  step: "Auto-update"

default: "true"

items:
  - id: "true"
    packages: []
    name: "Oui"
    description: "Activer les mises à jour automatiques"
  - id: "false"
    packages: []
    name: "Non"
    description: "Pas de mises à jour automatiques"
