####################################
#        HYPRLAND CONFIG           #
####################################

source = ./cfg/monitors.conf
source = ./cfg/environment.conf
source = ./cfg/autostart.conf
source = ./cfg/input.conf
source = ./cfg/appearance.conf
source = ./cfg/animations.conf
source = ./cfg/workspaces.conf
source = ./cfg/rules.conf
source = ./cfg/keybinds.conf
source = ./cfg/misc.conf
