-- Roudix Hyprland 0.55+ (Lua configuration)
-- Nix generates config/nix-plugins.lua so packaged plugins are loaded first.
require("config.nix-plugins")
-- Modularized for Roudix: common settings + common/apps/gaming rules + shell-specific binds.
require("config.colors")
require("config.defaults")
require("config.animations")
require("config.autostart")
require("config.decorations")
require("config.environment")
require("config.input")
require("config.layout")
require("config.misc")
require("config.monitors")
require("config.workspaces")
require("config.binds.common")
require("config.rules.common")
require("config.rules.apps")
require("config.rules.gaming")
require("config.shell")
