## _appearance.nix — Umbriel: [appearance], [appearance.blur],
## [appearance.shadow].
##
## Colors ([colors], border_focused/unfocused, insert_hint_color) are NOT
## set here: Umbriel has a native include mechanism
## (programs.umbriel.settings.include.files, see _include-noctalia.nix)
## that loads ~/.config/umbriel/noctalia.toml, regenerated live by
## Noctalia's matugen on every wallpaper change.
{ ... }:
{
  programs.umbriel.settings = {
    appearance = {
      prefer_no_csd = true;
      corner_radius = 0;

      blur = {
        enabled = true;
        optimized = true;
        passes = 2;
        noise = 0.03;
        saturation = 1.0;
      };

      # Bar of a tab group (ec677ac). Colors ([colors.tab_bar]) keep Umbriel's
      # defaults unless the included noctalia.toml provides them.
      tab_bar = {
        style = "titles";
        hide_when_single = true; # no bar (and no reserved space) for a one-window group
      };

      shadow = {
        enabled = true;
        # `color` is no longer a key under [appearance.shadow]: shadow
        # color is [colors].shadow, handled by the included noctalia.toml
        # (regenerated by matugen on every wallpaper change).
      };
    };
  };
}
