## _general.nix — Umbriel: [general], [environment], [workspaces],
## [overview] and [hot_corners].
##
## Docs: https://docs.noctalia.dev/umbriel/configuration/
##       https://docs.noctalia.dev/umbriel/workspace-overview/
{ ... }:
{
  programs.umbriel.settings = {
  general = {
    autostart = [ "noctalia" "discord" ];
    # ⚠ "xwayland-satellite" isn't in autostart: Umbriel spawns it itself
    # via `xwayland = true` (built into the compositor).
    mod_key = "Super";
    xwayland = true;
    show_cheatsheet = false; # niri: hotkey-overlay { skip-at-startup }
    focus_on_activate = false;
    # Apps like Steam/PrismLauncher that reopen already maximized stay
    # that way instead of being re-tiled on open.
    honor_restored_maximize = true;
  };

  environment = {
    LD_PRELOAD = "";
    MOZ_ENABLE_WAYLAND = "1";
    MOZ_DBUS_REMOTE = "1";
    GDK_BACKEND = "wayland";
    QT_AUTO_SCREEN_SCALE_FACTOR = "1";
    QT_WAYLAND_FORCE_DPI = "physical";
    EGL_PLATFORM = "wayland";
    CLUTTER_BACKEND = "wayland";
    TERM = "ghostty";
    TERMINAL = "ghostty";
    QT_QPA_PLATFORM= "xcb";
    _JAVA_AWT_WM_NONREPARENTING = "1";
    ELECTRON_OZONE_PLATFORM_HINT = "auto";
    QT_QPA_PLATFORMTHEME = "qt6ct";
    QT_QPA_PLATFORMTHEME_QT6 = "qt6ct";
    GTK_IM_MODULE = "simple";
  };

  workspaces.back_and_forth = true; # niri: workspace-auto-back-and-forth

  # ── Overview (Mod+O) ──────────────────────────────────────────
  # Uses appearance.blur for a background consistent with the rest of the
  # theme.
  overview = {
    zoom = 0.5;
    background_blur = true;
    # background_tint / workspace_background are no longer [overview]
    # keys — they moved to [colors.overview], handled by the included
    # noctalia.toml (regenerated by matugen on every wallpaper change).
    # See _include-noctalia.nix.
  };

  # ── Hot corners ──────────────────────────────────────────────────────────
  # Native Umbriel feature with no direct niri equivalent. Only the
  # top-left corner is enabled by default (overview); the other 3 can be
  # added the same way (top_right / bottom_left / bottom_right).
  hot_corners.top_left = {
    enabled = true;
    delay_ms = 300;
    action = "overview-toggle";
  };
  };
}
