# ──────────────────────────────────────
# MISC
# ──────────────────────────────────────
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    focus_on_activate = true
    vfr = true
    vrr = 2                     # VRR on-demand (matches niri's variable-refresh-rate on-demand=true)
}

# Screenshot path
# Note: set this in your screenshot tool (grimblast, grim...) instead
# niri equivalent: ~/Pictures/niri-screenshots/ from %Y-%m-%d %H-%M-%S.png
