## _include-noctalia.nix — appends `include optional=true "noctalia.kdl"`
## to the end of the config.kdl generated by niri-flake
## (programs.niri.settings), so the theme Noctalia regenerates live
## (matugen) applies on top. Technique from github.com/Ly-sec/nixos
## (desktops/niri/home/noctalia-include.nix): `finalConfig` is the
## rendered KDL output from `.settings` (readonly); we concatenate it with
## the include text, then revalidate with `niri validate` before
## overwriting `xdg.configFile.niri-config`.
{ config, pkgs, lib, ... }:
let
  niriPkg = config.programs.niri.package;
  withNoctalia = config.programs.niri.finalConfig + ''

    include optional=true "noctalia.kdl"
  '';
in
{
  xdg.configFile.niri-config = lib.mkForce {
    target = "niri/config.kdl";
    force = true;
    source = pkgs.runCommand "config.kdl" {
      config = withNoctalia;
      passAsFile = [ "config" ];
      buildInputs = [ niriPkg ];
    } ''
      niri validate -c $configPath
      cp $configPath $out
    '';
  };
}
