{ config, lib, pkgs, inputs, username, ... }:
let
  isHyprland  = config.roudix.desktop.type == "hyprland";
  shellType   = config.roudix.desktop.shell or "noctalia";
  needsPolkit = shellType != "dms";
  isDms       = shellType == "dms";
  isNoctalia  = shellType == "noctalia";
  isKdeIntegration = config.roudix.desktopIntegration == "kde";
in
{
config = lib.mkIf isHyprland {

  # ── DMS greeter (when shell == dms or caelestia, i.e. !isNoctalia) ─────────
  programs.dms-greeter = lib.mkIf (!isNoctalia) {
    enable = true;
    compositor.name = "hyprland";
    configHome = "/home/${username}";
  };

  # ── DMS (shell) ─────────────────────────────────────────────────────────
  programs.dank-material-shell = lib.mkIf isDms {
    enable = true;
    systemd.enable = true;
  };

  # ── Noctalia greeter (when shell == noctalia) ──────────────────────────────
  services.displayManager.noctalia-greeter = lib.mkIf isNoctalia {
    enable = true;
    # Plain "hyprland" bypasses UWSM (graphical-session.target never
    # reached → xdg-desktop-portal.service fails as a dependency). Must
    # use the session generated by withUWSM = true: hyprland-uwsm.desktop.
    greeter-args = "--session hyprland-uwsm";
    settings = {
      keyboard = {
        layout  = config.roudix.keyboardLayout;
        variant = config.roudix.keyboardVariant;
      };
    };
  };

  programs.hyprland = {
    enable = true;
    withUWSM = true;
    xwayland.enable = true;
  };

  programs.uwsm.enable = true;

  xdg.portal = {
    enable = true;
    # xdg-desktop-portal-hyprland always stays top priority (ScreenCast) —
    # only the "fallback" portal (file pickers, etc.) follows
    # roudix.desktopIntegration.
    extraPortals = with pkgs;
      [ xdg-desktop-portal-hyprland ]
      ++ (if isKdeIntegration then [ kdePackages.xdg-desktop-portal-kde ] else [ xdg-desktop-portal-gtk ]);
    # "*" lets D-Bus arbitration pick between hyprland/gtk for each
    # interface on its own — non-deterministic, and can break randomly on
    # an update (see discourse.nixos.org, "Portals don't work on Hyprland
    # after update to 0.55.2"). We fix the priority order explicitly, as
    # recommended by the Hyprland wiki (hyprland;gtk), and pin ScreenCast
    # so it stays hyprland even if gtk/kde's registration order changed.
    config.common = {
      default = [ "hyprland" (if isKdeIntegration then "kde" else "gtk") ];
      "org.freedesktop.impl.portal.ScreenCast" = [ "hyprland" ];
    };
  };

  # ── Polkit agent ────────────────────────────────────────────────────────
  systemd.user.services.polkit-agent = {
    description =
      if isKdeIntegration
      then "KDE Polkit authentication agent"
      else "GNOME Polkit authentication agent";
    wantedBy = [ "graphical-session.target" ];
    after    = [ "graphical-session.target" ];
    partOf   = [ "graphical-session.target" ];
    serviceConfig = {
      Type       = "simple";
      ExecStart  =
        if isKdeIntegration
        then "${pkgs.kdePackages.polkit-kde-agent-1}/libexec/polkit-kde-authentication-agent-1"
        else "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1";
      Restart    = "on-failure";
      RestartSec = "1s";
    };
  };

  programs.nautilus-open-any-terminal = {
    enable = true;
    terminal = "ghostty";
  };

  # ── Keyring ───────────────────────────────────────────────────────────
  # ⚠ kde branch not tested in a real session. ly.nix enables "ly" as the
  # display manager for hyprland unconditionally (useLy = isHyprland,
  # regardless of isNoctalia), while this block keeps noctalia-greeter
  # (greetd) active when isNoctalia — so both DMs can run at the same time
  # when isNoctalia == true. That's a pre-existing conflict on ly.nix's
  # side, not introduced here. Until it's resolved there (either
  # isHyprland && !isNoctalia, or removing the noctalia-greeter block from
  # this file), the keyring is wired to both possible PAM services to stay
  # correct either way.
  # Separately known caveat: the "greetd" PAM service doesn't substack
  # "login" (nixpkgs#357201), which has already broken kwallet auto-unlock
  # for other greetd users — see discourse.nixos.org "Auto-Unlock kwallet
  # with greetd login-manager".
  services.gnome.gnome-keyring.enable = !isKdeIntegration;
  security.pam.services.ly.enableGnomeKeyring     = lib.mkIf (!isKdeIntegration) true;
  security.pam.services.greetd.enableGnomeKeyring = lib.mkIf (isNoctalia && !isKdeIntegration) true;
  security.pam.services.ly.kwallet.enable         = lib.mkIf isKdeIntegration true;
  security.pam.services.greetd.kwallet.enable     = lib.mkIf (isNoctalia && isKdeIntegration) true;


  environment.systemPackages = with pkgs; [
    awww
    grimblast
    playerctl
  ]
  ++ lib.optionals needsPolkit [ hyprpolkitagent ]
  ++ lib.optional (!isKdeIntegration) polkit_gnome
  ++ lib.optional isKdeIntegration kdePackages.polkit-kde-agent-1;
 };
}
