{ lib, ... }:
{
  # ── Icon theme (bare compositors only) ──────────────────────────────────
  # Read on the home-manager side (modules/home/theming/gtk-theme.nix) via osConfig
  # — same pattern as roudix.videoPlayer / roudix.discord / roudix.telegram.
  #
  # Only applies where modules/home/theming/gtk-theme.nix actually themes anything:
  # niri, hyprland, mangowc, umbriel. GNOME and KDE keep their own native
  # icon picker (GNOME Settings / System Settings) — this option has no
  # effect there.
  options.roudix.iconTheme = lib.mkOption {
    # Free-form string, not an enum: modules/home/theming/gtk-theme.nix special-cases
    # the curated ids below (installs the matching nixpkgs package) and
    # treats anything else as a literal GTK icon-theme name already present
    # on the system (roudix-switcher's icon-theme scan writes those) —
    # never a package reference, so a typo/unknown name can't break a
    # rebuild, it just falls back to hicolor icons at runtime.
    type    = lib.types.str;
    default = "papirus";
    description = ''
      Curated choices (each pulls in its own nixpkgs package):
        "papirus"  : Papirus-Dark — Roudix's original default.
        "tela"     : Tela-dark. When roudix.desktop.shell = "noctalia", this
                     is the Noctalia-recolored variant generated by
                     modules/home/theming/tela-icon.nix (~/.icons/Tela-dark-noctalia)
                     — first recolor happens on the next Noctalia
                     theme/accent change, not immediately on switch. Any
                     other shell falls back to plain Tela-dark from nixpkgs.
        "qogir"    : Qogir-dark (pkgs.qogir-icon-theme).
        "whitesur" : WhiteSur-dark (pkgs.whitesur-icon-theme).
        "colloid"  : Colloid-dark (pkgs.colloid-icon-theme).

      Any other value is taken as a literal icon-theme name (the folder's
      own name, e.g. "Numix-Circle") that you've made available yourself —
      via home.packages in modules/home/local.nix, or sitting in ~/.icons.
      roudix-switcher's "Icon Theme" page scans both locations and lists
      whatever it finds beyond the curated set above.
    '';
  };
}
