{ pkgs, inputs, config, lib, osConfig, dotfiles, ... }:
let
  shellType = osConfig.roudix.desktop.shell or "noctalia";
  mangowcDir = if shellType == "dms"
               then dotfiles + "/mangowc-dms"
               else dotfiles + "/mangowc";

  keyboardLayout = osConfig.roudix.keyboardLayout or "us";
  keyboardVariant = osConfig.roudix.keyboardVariant or "intl";

  terminalCmd = osConfig.roudix.terminal or "ghostty";
  fileManagerCmd = osConfig.roudix.fileManager or "nautilus";
  browserCmd = osConfig.roudix.browser.default or null;
in
{
  imports = [
    ../../theming/mangohud.nix
    ../../theming/papirus-icon.nix
    ../../theming/tela-icon.nix
  ];

  config = lib.mkIf (osConfig.roudix.desktop.type == "mangowc") {

    # ── Session target ──────────────────────────────────────────────────────
    # graphical-session.target is "static" (RefuseManualStart=yes): it can
    # only be reached via a target that BindsTo it. mango has no such
    # built-in mechanism here (wayland.windowManager.mango isn't used), so
    # it's recreated by hand. This is what unblocks xdg-desktop-portal.service.
    systemd.user.targets.mango-session = {
      Unit = {
        Description = "mango compositor session";
        Documentation = [ "man:systemd.special(7)" ];
        BindsTo = [ "graphical-session.target" ];
        Wants = [ "graphical-session-pre.target" ];
        After = [ "graphical-session-pre.target" ];
      };
    };

    # ── Config files ─────────────────────────────────────────────────────────
    xdg.configFile."mango" = {
      source    = mangowcDir;
      recursive = true;
    };

    # input.conf is generated by Nix (instead of being sourced as-is from
    # the store) solely to inject roudix.keyboardLayout /
    # roudix.keyboardVariant into it — the rest (mouse, touchpad, repeat)
    # is copied unchanged from the theme's static file.
    xdg.configFile."mango/generated-input.conf" = {
      force = true;
      text = ''
        # ──────────────────────────────────────
        # INPUT — KEYBOARD
        # ──────────────────────────────────────
        # Generated by Nix from roudix.keyboardLayout / roudix.keyboardVariant
        xkb_rules_layout=${keyboardLayout}
        xkb_rules_variant=${keyboardVariant}
        numlockon=1
        repeat_rate=25
        repeat_delay=600

        # ──────────────────────────────────────
        # INPUT — MOUSE
        # ──────────────────────────────────────
        accel_profile=1
        accel_speed=0.0

        # ──────────────────────────────────────
        # INPUT — TOUCHPAD
        # ──────────────────────────────────────
        tap_to_click=1
        tap_and_drag=1
        drag_lock=1
        trackpad_natural_scrolling=1
        disable_while_typing=1
      '';
    };

    # mango.conf is generated by Nix: absolute paths into the nix store
    # + an absolute source for user.conf to avoid any conflict with the
    # recursive one.
    xdg.configFile."mango/config.conf" = {
      force = true;
      text = ''
        source = ${mangowcDir}/cfg/environment.conf
        source = ${mangowcDir}/cfg/appearance.conf
        source = ${mangowcDir}/cfg/animations.conf
        source = ${config.home.homeDirectory}/.config/mango/generated-input.conf
        source = ${mangowcDir}/cfg/layout.conf
        source = ${mangowcDir}/cfg/monitors.conf
        source = ${mangowcDir}/cfg/workspaces.conf
        source = ${mangowcDir}/cfg/rules.conf
        source = ${mangowcDir}/cfg/keybinds.conf

        # ── Terminal / browser / file manager (resolved from roudix.*) ──
        source = ${config.home.homeDirectory}/.config/mango/apps.conf

        source = ${mangowcDir}/cfg/autostart.conf
        source = ${mangowcDir}/cfg/misc.conf

        # ── User overrides (injected by Nix) ─────────────────────────────
        source = ${config.home.homeDirectory}/.config/mango/user.conf
      '';
    };

    # apps.conf is generated by Nix: overrides SUPER+Return / SUPER+E / SUPER+B
    # (defined in keybinds.conf) + the TERM/TERMINAL env vars (defined in
    # environment.conf), with commands resolved from roudix.*. Sourced
    # after those two files in config.conf, so the values below win.
    # Note: SUPER+SHIFT,B (zen-twilight) is still handled by hand in
    # keybinds.conf, it's not an "extra" generated here.
    xdg.configFile."mango/apps.conf" = {
      force = true;
      text = ''
        # ── Generated by Nix from roudix.terminal / roudix.fileManager / roudix.browser ──
        env=TERM,${terminalCmd}
        env=TERMINAL,${terminalCmd}

        bind=SUPER,Return,spawn,${terminalCmd}
        bind=SUPER,E,spawn,${fileManagerCmd}
      '' + lib.optionalString (browserCmd != null) ''
        bind=SUPER,B,spawn,${browserCmd}
      '';
    };

    # ── User overrides file ───────────────────────────────────────────────────
    # Empty by default — the user fills it in home/local.nix.
    xdg.configFile."mango/user.conf" = {
      text = lib.mkDefault ''
        # Personal MangoWC overrides — edit this in home/local.nix
        # See home/local.nix.example for examples (monitors, keybinds, etc.)
      '';
    };

    home.file.".local/bin/screenshot.sh" = {
      executable = true;
      text = ''
        #!/bin/bash
        MODE=''${1:-zone}

        case "$MODE" in
            # Manual zone selection → Satty annotation
            zone)
                grim -g "$(slurp)" - | satty --filename -
                ;;
            # Output under the cursor → Satty annotation
            output)
                grim -o "$(slurp -o -f '%o')" - | satty --filename -
                ;;
            # Output under the cursor → straight to clipboard
            screen)
                grim -o "$(slurp -o -f '%o')" - | wl-copy
                ;;
        esac
      '';
    };

    # ── Packages ─────────────────────────────────────────────────────────────
    home.packages = with pkgs; [
      mangowc
      awww
      xwayland-satellite
      playerctl
      wl-clipboard
      pwvucontrol
      kdePackages.qtmultimedia
      mpvpaper
      grim
      slurp
      satty
      rofi


      # Apps
      gnome-text-editor
      gnome-disk-utility
      mission-center
      loupe
      gpu-screen-recorder

      # GTK theming
      nwg-look
      adw-gtk3
      papirus-icon-theme
      papirus-folders

      # Qt theming
      qt6Packages.qt6ct
      libsForQt5.qt5ct

      # Misc
      gvfs
      cava
    ]
    ++ lib.optionals (shellType == "noctalia") [
      inputs.noctalia.packages.${pkgs.stdenv.hostPlatform.system}.default
    ]
    ;
  };
}
