# ──────────────────────────────────────
# MONITORS
# ──────────────────────────────────────
# Run `hyprctl monitors` to list connected displays

# HKC 1080p@165 — left monitor
monitor = desc:HKC OVERSEAS LIMITED 24E4 0000000000001, 1920x1080@165, 0x0, 1

# Legion 1440p@240 — right monitor, VRR on-demand
monitor = desc:Lenovo Group Limited Legion 27Q-10 UNA07260, 2560x1440@240, 1920x0, 1, vrr, 2
