# ──────────────────────────────────────
# WORKSPACES
# ──────────────────────────────────────
# Workspace mapping from niri named workspaces:
#   󰈹  Browser   → ws 1  (Legion 1440p)
#      Code      → ws 2  (Legion 1440p)
#      Terminal  → ws 3  (HKC 1080p)
#      Chat      → ws 4  (Legion 1440p)
#   󰊗  Gaming    → ws 5  (Legion 1440p)
#   󰉋  Files     → ws 6  (Legion 1440p)
#   󰝚  Music     → ws 7  (HKC 1080p)
#      Misc      → ws 8  (HKC 1080p)

workspace = 1, monitor:desc:Lenovo Group Limited Legion 27Q-10 UNA07260, default:true
workspace = 2, monitor:desc:Lenovo Group Limited Legion 27Q-10 UNA07260
workspace = 3, monitor:desc:HKC OVERSEAS LIMITED 24E4 0000000000001
workspace = 4, monitor:desc:Lenovo Group Limited Legion 27Q-10 UNA07260
workspace = 5, monitor:desc:Lenovo Group Limited Legion 27Q-10 UNA07260
workspace = 6, monitor:desc:Lenovo Group Limited Legion 27Q-10 UNA07260
workspace = 7, monitor:desc:HKC OVERSEAS LIMITED 24E4 0000000000001
workspace = 8, monitor:desc:HKC OVERSEAS LIMITED 24E4 0000000000001
