animations=1
layer_animations=1

animation_type_open=zoom
animation_type_close=zoom
layer_animation_type_open=slide
layer_animation_type_close=slide

animation_fade_in=1
animation_fade_out=1

animation_duration_open=200
animation_duration_close=180
animation_duration_move=150
animation_duration_tag=180

# Courbes plus stables
animation_curve_open=0.25,0.46,0.45,0.94
animation_curve_close=0.33,1,0.68,1
animation_curve_move=0.22,1,0.36,1
animation_curve_tag=0.22,1,0.36,1
