# ──────────────────────────────────────
# ENVIRONMENT VARIABLES
# ──────────────────────────────────────
env=MOZ_ENABLE_WAYLAND,1
env=XDG_SESSION_TYPE,wayland
env=XDG_CURRENT_DESKTOP,mango
env=XDG_SESSION_DESKTOP,mango
env=MOZ_DBUS_REMOTE,1
env=GDK_BACKEND,wayland
env=QT_AUTO_SCREEN_SCALE_FACTOR,1
env=EGL_PLATFORM,wayland
env=CLUTTER_BACKEND,wayland
env=TERM,ghostty
env=TERMINAL,ghostty
env=_JAVA_AWT_WM_NONREPARENTING,1
env=ELECTRON_OZONE_PLATFORM_HINT,auto
env=QT_QPA_PLATFORMTHEME,qt6ct
env=XCURSOR_THEME,capitaine-cursors-white
env=XCURSOR_SIZE,32
