# ──────────────────────────────────────────────────────────────────
#  Keyboard
# ──────────────────────────────────────────────────────────────────
xkb_rules_layout=us
xkb_rules_variant=intl
numlockon=1


# ──────────────────────────────────────────────────────────────────
#  Mouse & Trackpad (clean MangoWC)
# ──────────────────────────────────────────────────────────────────

accel_profile=1
accel_speed=0.0

tap_to_click=1
trackpad_natural_scrolling=1

sloppyfocus=0
focus_follows_mouse_delay=150   # évite les changements trop rapides
