# ──────────────────────────────────────────────────────────────────
#  Scroller layout (optimized)
# ──────────────────────────────────────────────────────────────────

scroller_structs=10
scroller_default_proportion=0.5

scroller_focus_center=1
scroller_prefer_center=1

scroller_proportion_preset=0.33333,0.5,0.66667
