# ──────────────────────────────────────────────────────────────────
#  Misc (optimized)
# ──────────────────────────────────────────────────────────────────

cursor_theme=capitaine-cursors-white
cursor_size=32
cursor_hide_timeout=3

focus_on_activate=0
xwayland_persistence=1
