# ──────────────────────────────────────
# MONITORS
# ──────────────────────────────────────
# HKC 1080p@165  — moniteur gauche  → DP-3 (secondaire, pas de VRR)
# Legion 1440p@240 — moniteur droit → DP-1 (gaming, VRR + tearing)

# HKC — secondaire, pas de VRR ni tearing
monitorrule=name:DP-3,width:1920,height:1080,refresh:165,x:0,y:180,scale:1,vrr:0,rr:0

# Legion — principal gaming, VRR + tearing activé
# tearing:1 → permet au jeu de présenter les frames sans attendre le vblank
# combiné avec force_tearing dans rules.conf = latence minimale
monitorrule=name:DP-1,width:2560,height:1440,refresh:240,x:1920,y:0,scale:1,vrr:1,rr:0,tearing:1
