# ──────────────────────────────────────
# AUTOSTART
# ──────────────────────────────────────
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = awww-daemon
exec-once = discord
exec-once = openrgb
exec-once = noctalia-shell --no-duplicate
